<?php  if ( ! defined('BASEPATH')) exit('No direct script access allowed');

$config['empresa_nombre']       = 'Cafe Digital';
$config['empresa_razon_social'] = 'Centro de Impresión Digital Corte Laser y Cafetería';
$config['empresa_rfc']          = 'JAGF830204JM6';
$config['empresa_calle']        = 'Av. Conchita';
$config['empresa_num_ext']      = '#3768';
$config['empresa_num_int']      = 'A';
$config['empresa_colonia']      = 'Loma Bonita';
$config['empresa_municipio']    = 'Zapopan';
$config['empresa_estado']       = 'Jalisco';
$config['empresa_cp']           = '28500';
$config['empresa_telefono']     = '';
$config['empresa_url_logo']     = 'application/images/logo.png';
$config['empresa_url_logop']    = true;
$config['empresa_email']        = 'servicios@cafedigital.mx';
$config['empresa_pag_web']      = 'www.cafedigital.mx';
$config['empresa_footer']       = '';
$config['empresa_color_1']      = '';
$config['empresa_color_2']      = '';
$config['empresa_fuente_pv']    = '';